In [2]:
import sqlite3
import pandas as pd

In [3]:
conn = sqlite3.connect("northwind.db")

In [4]:
query = """
SELECT name
FROM sqlite_master
WHERE type='table';
"""

tables = pd.read_sql(query, conn)
tables

                    name
0             Categories
1        sqlite_sequence
2   CustomerCustomerDemo
3   CustomerDemographics
4              Customers
5              Employees
6    EmployeeTerritories
7          Order Details
8                 Orders
9               Products
10               Regions
11              Shippers
12             Suppliers
13           Territories

In [15]:
query = """
SELECT
    p.ProductName,
    SUM(od.Quantity) AS Total_Quantity_Sold
FROM [Order Details] od
JOIN Products p
ON od.ProductID = p.ProductID
GROUP BY p.ProductName
ORDER BY Total_Quantity_Sold DESC
LIMIT 10;
"""

top_products = pd.read_sql(query, conn)
top_products

                       ProductName  Total_Quantity_Sold
0        Louisiana Hot Spiced Okra               206213
1           Sir Rodney's Marmalade               205637
2       Teatime Chocolate Biscuits               205487
3                   Sirop d'érable               205005
4              Gumbär Gummibärchen               204761
5                    Outback Lager               204403
6                   Ravioli Angelo               204251
7             Raclette Courdavault               204137
8  Uncle Bob's Organic Dried Pears               203970
9                    Sasquatch Ale               203667

In [16]:
query = """
SELECT
    c.CompanyName,
    ROUND(SUM(od.UnitPrice * od.Quantity * (1 - od.Discount)), 2) AS Revenue
FROM Customers c
JOIN Orders o
ON c.CustomerID = o.CustomerID
JOIN [Order Details] od
ON o.OrderID = od.OrderID
GROUP BY c.CompanyName
ORDER BY Revenue DESC
LIMIT 10;
"""

top_customers = pd.read_sql(query, conn)
top_customers

                          CompanyName     Revenue
0                                  IT  9745371.29
1                       B's Beverages  6154115.34
2          Hungry Coyote Import Store  5698023.67
3                       Rancho grande  5559110.08
4                 Gourmet Lanchonetes  5552309.80
5  Ana Trujillo Emparedados y helados  5534356.65
6                  Ricardo Adocicados  5524517.31
7                   Folies gourmandes  5505502.85
8                   Let's Stop N Shop  5462198.02
9                   LILA-Supermercado  5437438.34

In [17]:
query = """
SELECT
    strftime('%Y-%m', o.OrderDate) AS Month,
    ROUND(SUM(od.UnitPrice * od.Quantity * (1 - od.Discount)),2) AS Sales
FROM Orders o
JOIN [Order Details] od
ON o.OrderID = od.OrderID
GROUP BY Month
ORDER BY Month;
"""

monthly_sales = pd.read_sql(query, conn)
monthly_sales

       Month       Sales
0    2012-07  2066219.40
1    2012-08  3556875.79
2    2012-09  3440144.98
3    2012-10  3201529.96
4    2012-11  2980494.74
..       ...         ...
131  2023-06  3071787.73
132  2023-07  3350337.36
133  2023-08  3293158.67
134  2023-09  3544698.51
135  2023-10  2923364.35

[136 rows x 2 columns]

In [18]:
query = """
SELECT
    c.CategoryName,
    ROUND(SUM(od.UnitPrice * od.Quantity * (1 - od.Discount)),2) AS Revenue
FROM Categories c
JOIN Products p
ON c.CategoryID = p.CategoryID
JOIN [Order Details] od
ON p.ProductID = od.ProductID
GROUP BY c.CategoryName
ORDER BY Revenue DESC;
"""

categories = pd.read_sql(query, conn)
categories

     CategoryName      Revenue
0       Beverages  92163184.18
1     Confections  66337803.06
2    Meat/Poultry  64881147.97
3  Dairy Products  58018116.78
4      Condiments  55795126.78
5         Seafood  49921604.17
6         Produce  32701119.88
7  Grains/Cereals  28568530.34

In [19]:
query = """
SELECT
    c.CompanyName,
    COUNT(o.OrderID) AS Total_Orders
FROM Customers c
JOIN Orders o
ON c.CustomerID = o.CustomerID
GROUP BY c.CompanyName
ORDER BY Total_Orders DESC;
"""

purchase_frequency = pd.read_sql(query, conn)
purchase_frequency

                             CompanyName  Total_Orders
0                                     IT           335
1                          B's Beverages           210
2                     Ricardo Adocicados           203
3                      LILA-Supermercado           203
4                    Gourmet Lanchonetes           202
..                                   ...           ...
87                       Around the Horn           156
88                  La corne d'abondance           155
89        Furia Bacalhau e Frutos do Mar           155
90  FISSA Fabrica Inter. Salchichas S.A.           155
91                Océano Atlántico Ltda.           154

[92 rows x 2 columns]

In [10]:
top_products.head()

                  ProductName  Total_Quantity_Sold
0   Louisiana Hot Spiced Okra               206213
1      Sir Rodney's Marmalade               205637
2  Teatime Chocolate Biscuits               205487
3              Sirop d'érable               205005
4         Gumbär Gummibärchen               204761

In [11]:
top_customers.head()

                  CompanyName     Revenue
0                          IT  9745371.29
1               B's Beverages  6154115.34
2  Hungry Coyote Import Store  5698023.67
3               Rancho grande  5559110.08
4         Gourmet Lanchonetes  5552309.80

In [12]:
monthly_sales.describe()

              Sales
count  1.360000e+02
mean   3.296961e+06
std    3.885097e+05
min    2.066219e+06
25%    3.050957e+06
50%    3.285466e+06
75%    3.518739e+06
max    4.377795e+06

In [13]:
categories.describe()

            Revenue
count  8.000000e+00
mean   5.604833e+07
std    2.010646e+07
min    2.856853e+07
25%    4.561648e+07
50%    5.690662e+07
75%    6.524531e+07
max    9.216318e+07

In [14]:
purchase_frequency.describe()

       Total_Orders
count     92.000000
mean     176.978261
std       20.942086
min      154.000000
25%      165.750000
50%      175.000000
75%      184.250000
max      335.000000

In [20]:
conn.close()